# -*- coding: utf-8 -*-
# Part 1: greetings (50) + smalltalk (70) + daily (75) + family (55) = 250

DATA = [
("greetings", "ทักทาย เปิดบทสนทนา", [
    ("Hi, how are you?", "สวัสดี สบายดีไหม", "how", 1),
    ("How's it going?", "เป็นไงบ้าง", "going", 1),
    ("What's up?", "ว่าไง / มีอะไรเหรอ", "up", 1),
    ("How have you been?", "ช่วงนี้เป็นไงบ้าง", "been", 1),
    ("Long time no see.", "ไม่เจอกันนานเลย", "Long", 1),
    ("It's been a while.", "ผ่านมานานแล้วนะ", "while", 1),
    ("Good to see you again.", "ดีใจที่ได้เจอคุณอีกครั้ง", "again", 1),
    ("Nice to meet you.", "ยินดีที่ได้รู้จัก", "meet", 1),
    ("The pleasure is mine.", "ยินดีเช่นกันครับ / ด้วยความยินดีครับ", "pleasure", 2),
    ("What brings you here?", "อะไรทำให้คุณมาที่นี่", "brings", 2),
    ("How's everything going?", "ทุกอย่างเป็นยังไงบ้าง", "everything", 1),
    ("How are things at home?", "ที่บ้านเป็นยังไงบ้าง", "things", 2),
    ("How's your family?", "ครอบครัวคุณเป็นยังไงบ้าง", "family", 1),
    ("Are you feeling okay?", "คุณรู้สึกโอเคไหม", "feeling", 1),
    ("You look great today.", "วันนี้คุณดูดีมาก", "great", 1),
    ("You look tired.", "คุณดูเหนื่อยๆ นะ", "tired", 1),
    ("Did you sleep well?", "นอนหลับดีไหม", "sleep", 1),
    ("I slept like a baby.", "นอนหลับสนิทมาก", "baby", 2),
    ("I'm doing fine, thanks.", "ฉันสบายดี ขอบคุณ", "fine", 1),
    ("I can't complain.", "ก็ยังดี ไม่มีอะไรให้บ่น", "complain", 2),
    ("Same as usual.", "เหมือนเดิม", "usual", 2),
    ("Nothing much.", "ก็ไม่มีอะไร", "Nothing", 1),
    ("What have you been up to?", "ช่วงนี้ทำอะไรอยู่", "up", 2),
    ("Just working as usual.", "ก็ทำงานตามปกติ", "working", 2),
    ("I've been pretty busy.", "ฉันค่อนข้างยุ่งเลย", "busy", 2),
    ("Well, look who's here!", "เฮ้ ดูสิใครมา", "who", 2),
    ("Fancy meeting you here.", "บังเอิญมาเจอกันที่นี่ได้", "Fancy", 2),
    ("Small world, isn't it?", "โลกกลมจริงๆ นะ", "world", 2),
    ("It's so nice outside.", "ข้างนอกดีมากเลย", "outside", 1),
    ("How was your weekend?", "สุดสัปดาห์เป็นยังไงบ้าง", "weekend", 1),
    ("Did you have a good weekend?", "สุดสัปดาห์สบายดีไหม", "good", 1),
    ("My weekend was great.", "สุดสัปดาห์ของฉันดีมาก", "great", 1),
    ("What did you do last night?", "เมื่อคืนทำอะไร", "night", 1),
    ("I just stayed home.", "ก็แค่อยู่บ้าน", "stayed", 2),
    ("Let's catch up sometime.", "ว่างๆ เจอกันคุยกันบ้างนะ", "catch", 2),
    ("We should talk more often.", "เราควรคุยกันบ่อยกว่านี้", "often", 2),
    ("How do you know her?", "คุณรู้จักเธอได้ยังไง", "know", 1),
    ("We went to school together.", "เราเรียนโรงเรียนเดียวกัน", "school", 1),
    ("I've heard a lot about you.", "ได้ยินเรื่องของคุณมามาก", "heard", 2),
    ("I've heard nothing but good things about you!", "ฉันได้ยินแต่เรื่องดีๆ เกี่ยวกับคุณมาตลอดเลย!", "nothing", 2),
    ("You have a nice smile.", "คุณยิ้มสวยจัง", "smile", 1),
    ("Thanks for coming today.", "ขอบคุณที่มาวันนี้", "coming", 1),
    ("I'm glad you could make it.", "ดีใจที่คุณมาได้", "make", 2),
    ("Welcome to our place.", "ยินดีต้อนรับสู่บ้านเรา", "Welcome", 1),
    ("Make yourself at home.", "ตามสบายเหมือนอยู่บ้านเลยนะ", "home", 1),
    ("Can I get you a drink?", "รับเครื่องดื่มอะไรไหม", "drink", 1),
    ("Would you like some coffee?", "อยากได้กาแฟไหม", "coffee", 1),
    ("Have a seat.", "เชิญนั่งเลย", "seat", 1),
    ("Let me introduce you to everyone.", "ให้ฉันแนะนำคุณให้รู้จักทุกคนนะ", "introduce", 3),
    ("Everyone, this is my friend John.", "ทุกคน นี่คือเพื่อนของฉันชื่อจอห์น", "friend", 2),
]),
("smalltalk", "สนทนาทั่วไป", [
    ("What do you do for a living?", "คุณทำงานอะไร", "living", 1),
    ("I'm a teacher.", "ฉันเป็นครู", "teacher", 1),
    ("Where do you work?", "คุณทำงานที่ไหน", "work", 1),
    ("How long have you worked there?", "ทำงานที่นั่นมานานแค่ไหน", "worked", 2),
    ("I've been there for five years.", "อยู่ที่นั่นมาห้าปีแล้ว", "years", 2),
    ("Do you like your job?", "คุณชอบงานของคุณไหม", "job", 1),
    ("I love what I do.", "ฉันรักงานที่ทำ", "love", 1),
    ("It's a bit stressful sometimes.", "บางทีก็เครียดหน่อยๆ", "stressful", 2),
    ("Where are you from originally?", "แต่เดิมคุณมาจากไหน", "originally", 3),
    ("I'm from Bangkok.", "ฉันมาจากกรุงเทพฯ", "Bangkok", 1),
    ("What part of Thailand are you from?", "มาจากภาคไหนของไทย", "part", 2),
    ("Do you live around here?", "คุณอยู่แถวนี้ไหม", "around", 2),
    ("I live nearby.", "ฉันอยู่ใกล้ๆ นี้", "nearby", 2),
    ("It's about ten minutes away.", "ไกลออกไปประมาณสิบนาที", "minutes", 2),
    ("How long does it take to get there?", "ใช้เวลาเดินทางนานแค่ไหน", "take", 2),
    ("It takes about thirty minutes.", "ใช้เวลาประมาณครึ่งชั่วโมง", "thirty", 2),
    ("Do you come here often?", "คุณมาที่นี่บ่อยไหม", "often", 1),
    ("This is my first time here.", "นี่เป็นครั้งแรกที่มาที่นี่", "first", 1),
    ("I come here every week.", "ฉันมาที่นี่ทุกอาทิตย์", "every", 1),
    ("What do you think about it?", "คุณคิดยังไงกับเรื่องนี้", "think", 1),
    ("In my opinion, it's worth it.", "ในความคิดของฉัน มันคุ้มค่า", "opinion", 3),
    ("I couldn't agree more.", "เห็นด้วยสุดๆ", "agree", 2),
    ("That's a good point.", "นั่นเป็นประเด็นที่ดี", "point", 2),
    ("I never thought about it that way.", "ฉันไม่เคยคิดแบบนั้นเลย", "thought", 3),
    ("You have a point there.", "คุณก็มีเหตุผลนะ", "point", 2),
    ("Let's change the subject.", "เปลี่ยนเรื่องกันเถอะ", "subject", 3),
    ("Speaking of which...", "พูดถึงเรื่องนั้น...", "Speaking", 2),
    ("By the way, how's your brother?", "อ้อ แล้วพี่ชายคุณเป็นไงบ้าง", "brother", 2),
    ("Anyway, back to the topic.", "เอาล่ะ กลับมาที่เรื่องเดิม", "topic", 3),
    ("Where were we?", "เราคุยกันค้างไว้ตรงไหน", "were", 2),
    ("I totally forgot what I was saying.", "ลืมไปเลยว่าจะพูดอะไร", "forgot", 2),
    ("Give me a second to think.", "ขอเวลาคิดแป๊บนึง", "second", 1),
    ("That's interesting.", "น่าสนใจดี", "interesting", 1),
    ("Really? That's surprising.", "จริงเหรอ น่าแปลกใจ", "surprising", 2),
    ("I didn't know that.", "ฉันไม่รู้มาก่อนเลย", "know", 1),
    ("That explains everything.", "นั่นอธิบายทุกอย่างได้", "explains", 3),
    ("Now it makes sense.", "ตอนนี้ก็เข้าใจขึ้นแล้ว", "sense", 2),
    ("Is that so?", "อย่างนั้นเหรอ", "so", 1),
    ("Tell me more about it.", "เล่าให้ฟังเพิ่มอีกหน่อย", "more", 1),
    ("What happened next?", "แล้วเกิดอะไรขึ้นต่อ", "happened", 1),
    ("And then what?", "แล้วหลังจากนั้นล่ะ", "then", 1),
    ("How did it end?", "จบลงยังไง", "end", 1),
    ("That sounds amazing.", "ฟังดูสุดยอดเลย", "amazing", 1),
    ("That must have been scary.", "คงน่ากลัวมากแน่ๆ", "scary", 2),
    ("I bet you were worried.", "เดาว่าคุณคงกังวลมาก", "worried", 2),
    ("I'm happy to hear that.", "ดีใจที่ได้ยินแบบนั้น", "hear", 1),
    ("I'm sorry to hear that.", "เสียใจด้วยที่ได้ยินแบบนั้น", "sorry", 1),
    ("That's too bad.", "แย่จังเลย", "bad", 1),
    ("What a shame.", "น่าเสียดายจริงๆ", "shame", 2),
    ("Don't worry, it'll be fine.", "ไม่ต้องกังวล เดี๋ยวมันจะดีเอง", "worry", 1),
    ("Everything will work out.", "ทุกอย่างจะผ่านไปด้วยดี", "work", 2),
    ("Cheer up!", "ร่าเริงหน่อยนะ / ยิ้มเข้าไว้", "Cheer", 1),
    ("Things could be worse.", "มันอาจจะแย่กว่านี้ก็ได้", "worse", 2),
    ("Look on the bright side.", "มองในแง่ดีสิ", "bright", 3),
    ("There's always a solution.", "ทางแก้มันมีเสมอ", "solution", 3),
    ("Let's not talk about it now.", "ตอนนี้ยังไม่ต้องพูดถึงเรื่องนั้น", "talk", 2),
    ("I'd rather not discuss that.", "ฉันไม่อยากคุยเรื่องนั้น", "discuss", 3),
    ("Can we talk about something else?", "คุยเรื่องอื่นแทนได้ไหม", "else", 2),
    ("I don't feel comfortable talking about it.", "ฉันไม่ค่อยสะดวกใจจะพูดเรื่องนั้น", "comfortable", 3),
    ("Let's keep it between us.", "เก็บไว้ระหว่างเราสองคนนะ", "between", 3),
    ("Promise you won't tell anyone.", "สัญญาว่าจะไม่บอกใคร", "Promise", 2),
    ("I'll keep it a secret.", "ฉันจะเก็บเป็นความลับ", "secret", 2),
    ("It's our little secret.", "เป็นความลับระหว่างเราสองคน", "secret", 2),
    ("Word of mouth travels fast.", "ข่าวมันแพร่เร็ว", "mouth", 3),
    ("I heard through the grapevine.", "ได้ยินข่าวแว่วๆ มา", "grapevine", 3),
    ("Let's not jump to conclusions.", "อย่าเพิ่งด่วนสรุป", "conclusions", 3),
    ("We need more facts first.", "เราต้องหาข้อมูลเพิ่มก่อน", "facts", 3),
    ("Don't judge a book by its cover.", "อย่าตัดสินคนจากรูปลักษณ์ภายนอก", "judge", 3),
    ("Appearances can be deceiving.", "รูปลักษณ์ภายนอกหลอกได้", "Appearances", 3),
    ("You never know until you try.", "ไม่ลองก็ไม่รู้", "try", 2),
    ("It's worth a shot.", "ลองดูก็คุ้ม", "shot", 3),
    ("Better safe than sorry.", "ปลอดภัยไว้ก่อนดีกว่า", "safe", 2),
]),
("daily", "ชีวิตประจำวัน", [
    ("I wake up at six every morning.", "ฉันตื่นนอนหกโมงเช้าทุกวัน", "wake", 1),
    ("My alarm didn't go off.", "นาฬิกาปลุกไม่ดัง", "alarm", 2),
    ("I hit the snooze button.", "ฉันกดปุ่มพักนาฬิกาปลุก", "snooze", 3),
    ("I overslept this morning.", "เมื่อเช้าตื่นสาย", "overslept", 2),
    ("I need to hurry up.", "ฉันต้องรีบแล้ว", "hurry", 1),
    ("I'm running late for work.", "ฉันกำลังจะไปทำงานสาย", "late", 1),
    ("I take a shower every morning.", "ฉันอาบน้ำทุกเช้า", "shower", 1),
    ("I brush my teeth twice a day.", "ฉันแปรงฟันวันละสองครั้ง", "teeth", 1),
    ("I get dressed for work.", "ฉันแต่งตัวไปทำงาน", "dressed", 2),
    ("I have breakfast at seven.", "ฉันทานอาหารเช้าตอนเจ็ดโมง", "breakfast", 1),
    ("I usually have coffee in the morning.", "ปกติฉันดื่มกาแฟตอนเช้า", "coffee", 1),
    ("I read the news while eating.", "ฉันอ่านข่าวระหว่างทานข้าว", "news", 2),
    ("I take the bus to work.", "ฉันนั่งรถเมล์ไปทำงาน", "bus", 1),
    ("I drive to the office.", "ฉันขับรถไปออฟฟิศ", "drive", 1),
    ("The traffic was terrible.", "รถติดมาก", "traffic", 2),
    ("I got stuck in traffic.", "ฉันเจอรถติดหนักมาก / รถติดแหง็กเลย", "stuck", 2),
    ("I clock in at nine.", "ฉันลงเวลางานเก้าโมง", "clock", 3),
    ("I check my email first thing.", "ฉันเช็คอีเมลสิ่งแรกเลย", "email", 2),
    ("I have a meeting at ten.", "ฉันมีประชุมตอนสิบโมง", "meeting", 1),
    ("I eat lunch at noon.", "ฉันทานข้าวเที่ยงตอนเที่ยง", "lunch", 1),
    ("I usually eat out for lunch.", "ปกติฉันทานข้าวเที่ยงข้างนอก", "out", 2),
    ("I'm on my lunch break.", "ฉันกำลังพักเที่ยง", "break", 1),
    ("I finish work at six.", "ฉันเลิกงานหกโมง", "finish", 1),
    ("I clock out at six.", "ฉันลงเวลาออกตอนหกโมง", "clock", 3),
    ("I go home after work.", "ฉันกลับบ้านหลังเลิกงาน", "home", 1),
    ("I cook dinner at home.", "ฉันทำอาหารเย็นที่บ้าน", "cook", 1),
    ("We're ordering takeout tonight.", "คืนนี้เราสั่งอาหารมากินกัน", "takeout", 2),
    ("I wash the dishes after dinner.", "ฉันล้างจานหลังทานเย็น", "dishes", 1),
    ("I watch TV in the evening.", "ฉันดูทีวีตอนเย็น", "TV", 1),
    ("I scroll through my phone.", "ฉันเลื่อนดูโทรศัพท์", "scroll", 3),
    ("I read before going to bed.", "ฉันอ่านหนังสือก่อนนอน", "read", 1),
    ("I go to bed around eleven.", "ฉันเข้านอนประมาณห้าทุ่ม", "bed", 1),
    ("I can't fall asleep easily.", "ฉันนอนหลับยาก", "asleep", 2),
    ("I set my alarm before sleeping.", "ฉันตั้งนาฬิกาปลุกก่อนนอน", "alarm", 2),
    ("I forgot to buy groceries.", "ลืมซื้อของเข้าบ้าน", "groceries", 2),
    ("The fridge is empty.", "ตู้เย็นว่างเปล่า", "empty", 2),
    ("We're out of milk.", "นมหมดแล้ว", "milk", 1),
    ("I need to go to the store.", "ฉันต้องไปร้านค้า", "store", 1),
    ("I'll be back in an hour.", "ฉันจะกลับมาในอีกหนึ่งชั่วโมง", "hour", 1),
    ("I'm just going to the bank.", "ฉันแค่จะไปธนาคาร", "bank", 1),
    ("I need to withdraw some cash.", "ฉันต้องกดเงินสด", "withdraw", 2),
    ("I'll pay by card.", "ฉันจะจ่ายด้วยบัตร", "card", 1),
    ("I left my wallet at home.", "ฉันลืมกระเป๋าสตางค์ไว้ที่บ้าน", "wallet", 2),
    ("Did you see my keys?", "เห็นกุญแจฉันไหม", "keys", 1),
    ("I can't find my phone.", "หาโทรศัพท์ไม่เจอ", "find", 1),
    ("I left my phone at the office.", "ฉันลืมโทรศัพท์ไว้ที่ออฟฟิศ", "left", 2),
    ("My phone is dead.", "โทรศัพท์แบตหมด", "dead", 2),
    ("I need to charge my phone.", "ฉันต้องชาร์จโทรศัพท์", "charge", 1),
    ("Do you have a charger?", "มีที่ชาร์จไหม", "charger", 2),
    ("I'm out of battery.", "แบตเตอรี่หมด", "battery", 2),
    ("The Wi-Fi is not working.", "ไวไฟใช้ไม่ได้", "Wi-Fi", 1),
    ("The internet is slow today.", "อินเทอร์เน็ตช้าจังวันนี้", "internet", 2),
    ("I can't connect to the network.", "เชื่อมต่อเน็ตเวิร์กไม่ได้", "connect", 2),
    ("Please turn off the lights.", "กรุณาปิดไฟ", "lights", 1),
    ("Don't forget to lock the door.", "อย่าลืมล็อกประตู", "lock", 1),
    ("Lock the door behind you.", "ล็อกประตูตามหลังด้วย", "Lock", 1),
    ("Close the window, please.", "ปิดหน้าต่างหน่อย", "Close", 1),
    ("It's cold in here.", "ที่นี่หนาวจัง", "cold", 1),
    ("Turn on the heater.", "เปิดเครื่องทำความร้อน", "heater", 2),
    ("Could you crank up the AC? It's boiling hot in here.", "ช่วยเร่งแอร์หน่อยได้ไหม ข้างในนี้ร้อนอบอ้าวมาก", "crank", 2),
    ("Could you lower the volume?", "ช่วยลดเสียงหน่อยได้ไหม", "volume", 2),
    ("It's too loud in here.", "ที่นี่ดังเกินไป", "loud", 1),
    ("I need some peace and quiet.", "ฉันต้องการความเงียบสงบ", "peace", 2),
    ("Please keep it down.", "ช่วยเงียบๆ หน่อย", "down", 2),
    ("Make sure everything is turned off.", "ตรวจสอบให้แน่ใจว่าปิดทุกอย่างแล้ว", "turned", 2),
    ("I have a lot to do today.", "วันนี้ฉันมีอะไรต้องทำเยอะ", "lot", 1),
    ("Let me make a to-do list.", "ขอเขียนลิสต์สิ่งที่ต้องทำก่อน", "list", 2),
    ("I need to prioritize my tasks.", "ฉันต้องจัดลำดับความสำคัญของงาน", "prioritize", 3),
    ("I'm behind schedule.", "ฉันล่าช้ากว่ากำหนด", "schedule", 2),
    ("I'm ahead of schedule.", "ฉันเสร็จเร็วกว่ากำหนด", "ahead", 3),
    ("I'll do it right away.", "ฉันจะทำทันที", "away", 1),
    ("Let's get started.", "เริ่มกันเลย", "started", 1),
    ("I'm almost done.", "ฉันเกือบเสร็จแล้ว", "almost", 1),
    ("I've just finished.", "ฉันเพิ่งทำเสร็จ", "finished", 1),
    ("Good job, everyone.", "ทำได้ดีมาก ทุกคน", "job", 1),
]),
("family", "ครอบครัว บ้าน", [
    ("This is my mother.", "นี่คือแม่ของฉัน", "mother", 1),
    ("This is my father.", "นี่คือพ่อของฉัน", "father", 1),
    ("These are my parents.", "นี่คือพ่อแม่ของฉัน", "parents", 1),
    ("I have two sisters.", "ฉันมีพี่สาวน้องสาวสองคน", "sisters", 1),
    ("I'm an only child.", "ฉันเป็นลูกคนเดียว", "only", 2),
    ("My brother is older than me.", "พี่ชายอายุมากกว่าฉัน", "brother", 2),
    ("My younger sister is in college.", "น้องสาวฉันเรียนมหาวิทยาลัย", "college", 2),
    ("We look a lot alike.", "เราเหมือนกันมาก", "alike", 3),
    ("He takes after his father.", "เขาหน้าเหมือนพ่อ", "after", 2),
    ("She has her mother's eyes.", "เธอมีดวงตาเหมือนแม่", "eyes", 2),
    ("My grandparents live in the countryside.", "ปู่ย่าตายายอยู่ต่างจังหวัด", "grandparents", 2),
    ("We visit them every month.", "เราไปเยี่ยมพวกเขาทุกเดือน", "visit", 1),
    ("The whole family gathers for dinner.", "ทั้งครอบครัวรวมตัวกันทานข้าวเย็น", "gathers", 3),
    ("Family comes first.", "ครอบครัวต้องมาก่อน", "first", 2),
    ("Home is where the heart is.", "บ้านคือที่ที่หัวใจอยู่", "heart", 3),
    ("There's no place like home.", "ไม่มีที่ไหนเหมือนบ้าน", "place", 2),
    ("I miss my family.", "ฉันคิดถึงครอบครัว", "miss", 1),
    ("I call them every week.", "ฉันโทรหาพวกเขาทุกอาทิตย์", "call", 1),
    ("My mom is a great cook.", "แม่ฉันทำอาหารเก่งมาก", "cook", 1),
    ("My dad likes gardening.", "พ่อฉันชอบทำสวน", "gardening", 2),
    ("We have dinner together every night.", "เราทานข้าวเย็นด้วยกันทุกคืน", "together", 2),
    ("It's important to spend time with family.", "การใช้เวลากับครอบครัวสำคัญมาก", "important", 2),
    ("Let's have a family reunion.", "จัดงานรวมญาติกันเถอะ", "reunion", 3),
    ("How's your wife doing?", "ภรรยาเป็นยังไงบ้าง", "wife", 1),
    ("How's your husband?", "สามีเป็นยังไงบ้าง", "husband", 1),
    ("We've been married for ten years.", "เราแต่งงานกันมาสิบปีแล้ว", "married", 2),
    ("We got married last year.", "เราแต่งงานกันปีที่แล้ว", "married", 2),
    ("This is my son.", "นี่คือลูกชายของฉัน", "son", 1),
    ("This is my daughter.", "นี่คือลูกสาวของฉัน", "daughter", 1),
    ("The kids are playing outside.", "เด็กๆ กำลังเล่นอยู่ข้างนอก", "playing", 1),
    ("The children are asleep.", "เด็กๆ หลับแล้ว", "asleep", 2),
    ("Put the kids to bed.", "พาเด็กๆ เข้านอน", "bed", 2),
    ("Read them a bedtime story.", "อ่านนิทานก่อนนอนให้พวกเขาฟัง", "bedtime", 3),
    ("My baby is crying.", "ลูกของฉันร้องไห้", "crying", 1),
    ("The baby needs to be fed.", "ต้องให้นมลูกแล้ว", "fed", 3),
    ("I need to change the diaper.", "ฉันต้องเปลี่ยนผ้าอ้อม", "diaper", 3),
    ("My daughter just started school.", "ลูกสาวเพิ่งเริ่มเข้าโรงเรียน", "school", 2),
    ("My son is doing well in school.", "ลูกชายเรียนเก่ง", "well", 2),
    ("The kids are growing up so fast.", "เด็กๆ โตเร็วมาก", "growing", 2),
    ("I can't believe how big they've grown.", "ไม่อยากเชื่อว่าโตขนาดนี้แล้ว", "grown", 3),
    ("We're thinking about moving.", "เรากำลังคิดจะย้ายบ้าน", "moving", 2),
    ("We bought a new house.", "เราซื้อบ้านหลังใหม่", "bought", 2),
    ("We're renting an apartment.", "เราอยู่คอนโดเช่า", "renting", 3),
    ("The rent is a bit high.", "ค่าเช่าแพงไปหน่อย", "rent", 2),
    ("Our neighbor is very friendly.", "เพื่อนบ้านเราน่ารักมาก", "neighbor", 2),
    ("The neighbors are having a party.", "เพื่อนบ้านจัดปาร์ตี้กัน", "party", 2),
    ("Can you keep the noise down?", "ช่วยลดเสียงลงหน่อยได้ไหม", "noise", 2),
    ("It's very quiet in this area.", "บริเวณนี้เงียบสงบมาก", "quiet", 2),
    ("The apartment has a great view.", "คอนโดนี้วิวสวยมาก", "view", 2),
    ("We live on the tenth floor.", "เราอยู่ชั้นสิบ", "floor", 2),
    ("The elevator is out of order.", "ลิฟต์เสีย", "elevator", 3),
    ("I'll take the stairs.", "ฉันจะเดินขึ้นบันได", "stairs", 2),
    ("The house needs repairs.", "บ้านต้องซ่อมแล้ว", "repairs", 3),
    ("The roof is leaking.", "หลังคารั่ว", "roof", 2),
    ("The pipe is broken.", "ท่อน้ำแตก", "pipe", 3),
    ("We should repaint the walls.", "เราควรทาสีผนังใหม่", "repaint", 3),
    ("Let's clean the house this weekend.", "สุดสัปดาห์นี้ทำความสะอาดบ้านกันเถอะ", "clean", 2),
    ("I'll vacuum the living room.", "ฉันจะดูดฝุ่นห้องนั่งเล่น", "vacuum", 3),
    ("Please mop the floor.", "ช่วยถูพื้นหน่อย", "mop", 3),
    ("Take out the trash.", "เอาขยะไปทิ้ง", "trash", 2),
]),
]