# -*- coding: utf-8 -*-
# Part 2: food (65) + travel (60) + shopping (50) + work (65) = 240

DATA = [
("food", "อาหาร เครื่องดื่ม", [
    ("My stomach is growling, I need to get something to eat.", "ท้องฉันร้องจ๊อกๆ แล้ว ต้องหาอะไรกินหน่อย", "growling", 2),
    ("I'm starving.", "ฉันหิวมาก", "starving", 2),
    ("I could eat a horse.", "หิวมากจนกินได้ทั้งม้า", "horse", 3),
    ("What should we eat?", "เราควรกินอะไรดี", "eat", 1),
    ("I'm in the mood for pizza.", "อยากกินพิซซ่า", "mood", 2),
    ("Let's get something to eat.", "ไปหาอะไรกินกันเถอะ", "something", 1),
    ("I'll whip up something for dinner tonight.", "เดี๋ยวคืนนี้ฉันเข้าครัวทำอะไรให้กินเอง", "whip", 2),
    ("Do you want takeout?", "อยากสั่งอาหารกลับบ้านไหม", "takeout", 2),
    ("Let's order delivery.", "สั่งเดลิเวอรี่กันเถอะ", "delivery", 2),
    ("The delivery will take an hour.", "เดลิเวอรี่ใช้เวลาหนึ่งชั่วโมง", "delivery", 3),
    ("What do you want to order?", "อยากสั่งอะไร", "order", 1),
    ("I'll have a burger and fries.", "ฉันเอาเบอร์เกอร์กับเฟรนช์ฟรายส์", "burger", 1),
    ("Make that two, please.", "ขอเหมือนกันสองที่ครับ/ค่ะ", "two", 1),
    ("Can I see the menu?", "ขอดูเมนูหน่อยได้ไหม", "menu", 1),
    ("What do you recommend?", "แนะนำอะไรดี", "recommend", 2),
    ("The soup is really good here.", "ซุปที่นี่อร่อยมาก", "soup", 2),
    ("I'll have the grilled chicken.", "ฉันเอาไก่ย่าง", "grilled", 2),
    ("Is it spicy?", "เผ็ดไหม", "spicy", 1),
    ("I can't eat spicy food.", "ฉันกินเผ็ดไม่ได้", "spicy", 2),
    ("I'm allergic to peanuts.", "ฉันแพ้ถั่วลิสง", "allergic", 2),
    ("Do you have any allergies?", "คุณแพ้อะไรไหม", "allergies", 2),
    ("I don't eat meat.", "ฉันไม่กินเนื้อสัตว์", "meat", 1),
    ("I'm a vegetarian.", "ฉันเป็นมังสวิรัติ", "vegetarian", 2),
    ("Please make it less spicy.", "ช่วยทำเผ็ดน้อยๆ หน่อย", "less", 2),
    ("Could I get some water?", "ขอน้ำหน่อยได้ไหม", "water", 1),
    ("Can I have some more water?", "ขอน้ำเพิ่มได้ไหม", "more", 1),
    ("This is delicious!", "อันนี้อร่อยมาก", "delicious", 1),
    ("It tastes great.", "รสชาติดีมาก", "tastes", 1),
    ("This is too salty.", "เค็มเกินไป", "salty", 2),
    ("It's a bit sweet.", "หวานไปนิดหน่อย", "sweet", 2),
    ("The food here is amazing.", "อาหารที่นี่สุดยอด", "amazing", 2),
    ("I love Thai food.", "ฉันชอบอาหารไทย", "Thai", 1),
    ("Could you pass the salt?", "ช่วยส่งเกลือหน่อยได้ไหม", "salt", 1),
    ("Pass me the pepper, please.", "ส่งพริกไทยให้ฉันหน่อย", "pepper", 2),
    ("Could I get a knife and fork, please?", "ขอมีดกับส้อมหน่อยได้ไหมครับ/ค่ะ", "fork", 1),
    ("This fork is dirty.", "ส้อมนี้สกปรก", "dirty", 2),
    ("Can I get another plate?", "ขอจานใหม่อีกใบได้ไหม", "plate", 2),
    ("The portion is too big.", "ปริมาณเยอะเกินไป", "portion", 3),
    ("I'm completely stuffed, I couldn't eat another bite.", "ฉันอิ่มแปล้เลย กินต่ออีกคำไม่ไหวแล้ว", "stuffed", 2),
    ("I can't eat any more.", "กินไม่ไหวแล้ว", "more", 1),
    ("That was a great meal.", "มื้อนี้อร่อยมาก", "meal", 1),
    ("Let's have dessert.", "กินของหวานกันเถอะ", "dessert", 2),
    ("I have a sweet tooth.", "ฉันชอบของหวาน", "tooth", 3),
    ("What's for dessert?", "ของหวานมีอะไรบ้าง", "dessert", 2),
    ("I'll have some ice cream.", "ฉันเอาไอศกรีม", "ice", 1),
    ("Let me get the bill.", "คิดเงินหน่อย", "bill", 1),
    ("Can we have the check, please?", "ขอบิลหน่อยได้ไหม", "check", 1),
    ("I'll pay for dinner.", "ฉันจะจ่ายค่าข้าวเย็นเอง", "pay", 1),
    ("It's on me.", "ฉันเลี้ยงเอง", "me", 1),
    ("Let's split the bill.", "แยกจ่ายกันเถอะ", "split", 2),
    ("How much do I owe you?", "ฉันต้องจ่ายเท่าไหร่", "owe", 2),
    ("Keep the change.", "ไม่ต้องทอน", "change", 2),
    ("The service was great.", "บริการดีมาก", "service", 1),
    ("We should come here again.", "เราควรกลับมาที่นี่อีก", "again", 1),
    ("I'm parched, could I get a cold drink?", "คอแห้งเป็นผงเลย ขอเครื่องดื่มเย็นๆ สักแก้วได้ไหม", "parched", 2),
    ("Could I get a glass of juice?", "ขอน้ำผลไม้สักแก้วได้ไหม", "juice", 2),
    ("I'll have coffee, please.", "ขอกาแฟแก้วหนึ่งครับ/ค่ะ", "coffee", 1),
    ("Would you like tea or coffee?", "จะเอาชาหรือกาแฟ", "tea", 1),
    ("Make that two cups, please.", "ขอเป็นสองแก้วครับ/ค่ะ", "cups", 2),
    ("I need to buy some groceries.", "ฉันต้องไปซื้อของเข้าบ้าน", "groceries", 2),
    ("Let's go to the market.", "ไปตลาดกันเถอะ", "market", 1),
    ("The market is crowded.", "ตลาดคนเยอะมาก", "crowded", 2),
    ("I'll pick up some fruit.", "ฉันจะซื้อผลไม้หน่อย", "fruit", 2),
    ("These mangoes look ripe.", "มะม่วงพวกนี้สุกแล้ว", "ripe", 3),
    ("How much are these apples?", "แอปเปิลพวกนี้ราคาเท่าไหร่", "apples", 1),
]),
("travel", "เดินทาง สถานที่", [
    ("Where are we going?", "เราจะไปไหนกัน", "going", 1),
    ("I'm going to the airport.", "ฉันกำลังไปสนามบิน", "airport", 1),
    ("When does the flight leave?", "เที่ยวบินออกเมื่อไหร่", "flight", 2),
    ("The flight is at eight.", "เที่ยวบินตอนแปดโมง", "flight", 2),
    ("I need to catch my flight.", "ฉันต้องรีบไปขึ้นเครื่อง", "catch", 2),
    ("My flight was delayed.", "เที่ยวบินของฉันดีเลย์", "delayed", 2),
    ("My flight was canceled.", "เที่ยวบินของฉันถูกยกเลิก", "canceled", 2),
    ("Where is the check-in counter?", "เคาน์เตอร์เช็คอินอยู่ที่ไหน", "check-in", 2),
    ("Can I check in here?", "เช็คอินที่นี่ได้ไหม", "check", 1),
    ("I have a window seat.", "ฉันได้ที่นั่งติดหน้าต่าง", "window", 2),
    ("I prefer the aisle seat.", "ฉันชอบที่นั่งติดทางเดิน", "aisle", 3),
    ("Please fasten your seatbelt.", "กรุณารัดเข็มขัดนิรภัย", "seatbelt", 2),
    ("Keep your seatbelt fastened.", "รัดเข็มขัดไว้ตลอด", "fastened", 3),
    ("When do we land?", "เราลงจอดเมื่อไหร่", "land", 2),
    ("We'll land in two hours.", "เราจะลงจอดในอีกสองชั่วโมง", "land", 2),
    ("Where is my baggage?", "กระเป๋าเดินทางของฉันอยู่ไหน", "baggage", 2),
    ("I can't find my luggage.", "หากระเป๋าไม่เจอ", "luggage", 2),
    ("One of my bags is missing.", "กระเป๋าของฉันหายไปหนึ่งใบ", "missing", 2),
    ("Where is the exit?", "ทางออกอยู่ที่ไหน", "exit", 1),
    ("Where is the restroom?", "ห้องน้ำอยู่ที่ไหน", "restroom", 1),
    ("Where can I catch a taxi?", "นั่งแท็กซี่ได้ที่ไหน", "taxi", 1),
    ("Please take me to this address.", "ช่วยไปส่งที่อยู่นี้หน่อย", "address", 2),
    ("How much will the fare be?", "ค่าโดยสารเท่าไหร่", "fare", 2),
    ("Keep the change, please.", "ไม่ต้องทอนครับ", "change", 2),
    ("I need a hotel nearby.", "ฉันต้องหาที่พักใกล้ๆ", "hotel", 1),
    ("Do you have any vacancies?", "ยังมีห้องว่างไหม", "vacancies", 3),
    ("I'd like to book a room.", "ฉันอยากจองห้องพัก", "book", 2),
    ("For two nights, please.", "สองคืนครับ", "nights", 1),
    ("What time is check-in?", "เช็คอินกี่โมง", "check-in", 2),
    ("What time is check-out?", "เช็คเอาต์กี่โมง", "check-out", 2),
    ("Is breakfast included?", "รวมอาหารเช้าไหม", "included", 2),
    ("The room is too small.", "ห้องเล็กเกินไป", "small", 1),
    ("The room has a great view.", "ห้องนี้วิวดีมาก", "view", 2),
    ("The air conditioning is broken.", "แอร์เสีย", "conditioning", 3),
    ("Can you change my room?", "เปลี่ยนห้องให้ฉันได้ไหม", "change", 2),
    ("The Wi-Fi password, please.", "รหัสไวไฟหน่อย", "password", 2),
    ("I want to extend my stay.", "ฉันอยากขยายเวลาพัก", "extend", 3),
    ("Where is the train station?", "สถานีรถไฟอยู่ที่ไหน", "station", 1),
    ("Which platform is it?", "ชานชาลาไหน", "platform", 2),
    ("Does this train go to the city?", "รถไฟขบวนนี้ไปตัวเมืองไหม", "train", 2),
    ("How much is a ticket?", "ตั๋วราคาเท่าไหร่", "ticket", 1),
    ("I'd like a one-way ticket.", "ขอตั๋วเที่ยวเดียวใบหนึ่งครับ/ค่ะ", "one-way", 2),
    ("Two tickets, please.", "สองใบครับ", "tickets", 1),
    ("Where is the nearest bus stop?", "ป้ายรถเมล์ที่ใกล้ที่สุดอยู่ไหน", "bus", 2),
    ("Which bus goes to the museum?", "รถเมล์สายไหนไปพิพิธภัณฑ์", "museum", 2),
    ("How often does the bus come?", "รถเมล์มาทุกกี่นาที", "often", 2),
    ("I missed the last bus.", "พลาดรถเมล์เที่ยวสุดท้าย", "missed", 2),
    ("Could you pinpoint that on the map for me?", "ช่วยชี้พิกัดบนแผนที่ให้ฉันหน่อยได้ไหม", "pinpoint", 2),
    ("I think I've lost my way, could you help me with directions?", "ฉันคิดว่าฉันหลงทาง ช่วยบอกทางหน่อยได้ไหมครับ/ค่ะ", "directions", 2),
    ("Can you help me find this place?", "ช่วยหาที่นี่ให้ฉันหน่อยได้ไหม", "help", 2),
    ("Go straight ahead.", "ตรงไปข้างหน้า", "straight", 2),
    ("Turn left at the corner.", "เลี้ยวซ้ายที่หัวมุม", "left", 2),
    ("Turn right after the bank.", "เลี้ยวขวาหลังธนาคาร", "right", 2),
    ("It's across the street.", "อยู่ฝั่งตรงข้ามถนน", "across", 2),
    ("It's next to the bookstore.", "อยู่ติดกับร้านหนังสือ", "next", 2),
    ("Is it far from here?", "ไกลจากที่นี่ไหม", "far", 1),
    ("It's within walking distance.", "เดินไปได้", "walking", 2),
    ("How long does it take to walk there?", "เดินไปที่นั่นใช้เวลานานแค่ไหน", "walk", 1),
    ("Is this the right way?", "ทางนี้ถูกไหม", "right", 2),
]),
("shopping", "ซื้อของ เงิน", [
    ("Let's go shopping.", "ไปช้อปปิ้งกันเถอะ", "shopping", 1),
    ("I need to buy some clothes.", "ฉันต้องซื้อเสื้อผ้า", "clothes", 1),
    ("The store opens at ten.", "ร้านเปิดสิบโมง", "opens", 2),
    ("The store is closed today.", "วันนี้ร้านปิด", "closed", 1),
    ("What time does it close?", "ปิดกี่โมง", "close", 1),
    ("How much is this?", "อันนี้เท่าไหร่", "much", 1),
    ("Is there a discount?", "มีส่วนลดไหม", "discount", 1),
    ("Is this on sale?", "อันนี้ลดราคาไหม", "sale", 1),
    ("It's a bit expensive.", "แพงไปหน่อย", "expensive", 2),
    ("That's too expensive.", "แพงเกินไป", "expensive", 1),
    ("Is there any wiggle room on the price?", "พอจะลดหย่อนราคาลงได้อีกนิดไหมครับ/ค่ะ", "wiggle", 2),
    ("Is that the lowest you can go?", "นั่นคือลดได้สุดๆ เท่านี้แล้วใช่ไหม", "lowest", 2),
    ("I'll take it.", "ฉันเอาอันนี้", "take", 1),
    ("I'll take two.", "ฉันเอาสองอัน", "two", 1),
    ("Let me think about it.", "ขอคิดดูก่อน", "think", 1),
    ("I'm just looking, thanks.", "แค่ดูเล่นๆ ขอบคุณ", "looking", 1),
    ("Can I try this on?", "ลองตัวนี้ได้ไหม", "try", 1),
    ("Where is the fitting room?", "ห้องลองเสื้ออยู่ที่ไหน", "fitting", 2),
    ("It fits me perfectly.", "พอดีตัวมาก", "fits", 2),
    ("It's too small for me.", "เล็กไปสำหรับฉัน", "small", 2),
    ("Do you have a bigger size?", "มีไซส์ใหญ่กว่านี้ไหม", "bigger", 1),
    ("Do you have this in another color?", "มีตัวนี้สีอื่นไหม", "color", 2),
    ("I like this one.", "ฉันชอบอันนี้", "like", 1),
    ("This one is better.", "อันนี้ดีกว่า", "better", 1),
    ("Do you have anything cheaper?", "มีอันที่ถูกกว่านี้ไหม", "cheaper", 2),
    ("Where is the cashier?", "จุดชำระเงินอยู่ที่ไหน", "cashier", 2),
    ("I'd like to pay.", "ฉันขอจ่ายเงิน", "pay", 1),
    ("Can I pay by card?", "จ่ายด้วยบัตรได้ไหม", "card", 1),
    ("Do you accept cash?", "รับเงินสดไหม", "cash", 1),
    ("I'll pay in cash.", "ฉันจ่ายเป็นเงินสด", "cash", 1),
    ("Could I get a receipt?", "ขอบิลด้วยได้ไหม", "receipt", 2),
    ("Can I get a bag?", "ขอถุงหน่อยได้ไหม", "bag", 1),
    ("This bag is too small.", "ถุงนี้เล็กเกินไป", "bag", 2),
    ("Can I return this?", "คืนของได้ไหม", "return", 1),
    ("I'd like a refund.", "ฉันขอเงินคืน", "refund", 2),
    ("I need to exchange this.", "ฉันต้องเปลี่ยนของ", "exchange", 2),
    ("I have the receipt here.", "ฉันมีใบเสร็จอยู่ที่นี่", "receipt", 2),
    ("I lost the receipt.", "ฉันทำใบเสร็จหาย", "lost", 2),
    ("Can I return it without a receipt?", "คืนของโดยไม่มีใบเสร็จได้ไหม", "return", 3),
    ("This is defective.", "อันนี้มีตำหนิ", "defective", 3),
    ("It broke right away.", "เพิ่งซื้อก็พังแล้ว", "broke", 3),
    ("Is there a warranty?", "มีการรับประกันไหม", "warranty", 2),
    ("The warranty covers this.", "การรับประกันครอบคลุมกรณีนี้", "warranty", 3),
    ("Where is the customer service?", "จุดบริการลูกค้าอยู่ที่ไหน", "service", 2),
    ("I'd like to speak to the manager.", "ฉันอยากคุยกับผู้จัดการ", "manager", 2),
    ("This isn't what I ordered.", "นี่ไม่ใช่ที่ฉันสั่ง", "ordered", 2),
    ("The size is wrong.", "ไซส์ผิด", "wrong", 2),
    ("I'll come back tomorrow.", "พรุ่งนี้ฉันจะกลับมาใหม่", "back", 1),
    ("Can you hold this for me?", "ช่วยเก็บไว้ให้ฉันได้ไหม", "hold", 3),
    ("I'm ready to check out everything in my cart.", "ฉันพร้อมจะชำระเงินสินค้าทั้งหมดในตะกร้าแล้ว", "cart", 2),
]),
("work", "ทำงาน การเรียน", [
    ("I have to go to work.", "ฉันต้องไปทำงาน", "work", 1),
    ("I'm going to the office.", "ฉันกำลังไปออฟฟิศ", "office", 1),
    ("I work from home.", "ฉันทำงานที่บ้าน", "home", 1),
    ("I have a meeting now.", "ฉันมีประชุมตอนนี้", "meeting", 1),
    ("The meeting starts at ten.", "ประชุมเริ่มสิบโมง", "starts", 1),
    ("The meeting has been rescheduled.", "เลื่อนประชุมแล้ว", "rescheduled", 3),
    ("Can we reschedule the meeting?", "เลื่อนประชุมได้ไหม", "reschedule", 3),
    ("I'm running late for the meeting.", "ฉันจะไปประชุมสาย", "late", 1),
    ("Let's begin the meeting.", "เริ่มประชุมกันเลย", "begin", 2),
    ("Let's get down to business.", "เข้าสู่เรื่องงานกันเลย", "business", 3),
    ("I'll take the meeting minutes today.", "วันนี้ฉันจะช่วยจดบันทึกการประชุมให้นะ", "minutes", 2),
    ("Did everyone get the agenda?", "ทุกคนได้รับวาระการประชุมหรือยัง", "agenda", 3),
    ("Let's go over the schedule.", "มาดูตารางเวลากัน", "schedule", 2),
    ("We need to finish by Friday.", "เราต้องทำให้เสร็จภายในวันศุกร์", "Friday", 2),
    ("The deadline is tomorrow.", "กำหนดส่งคือพรุ่งนี้", "deadline", 2),
    ("Can we extend the deadline?", "ขยายกำหนดเวลาได้ไหม", "extend", 2),
    ("I'll work on it today.", "วันนี้ฉันจะทำเรื่องนี้", "work", 1),
    ("I'm almost done with the report.", "ฉันเกือบทำรายงานเสร็จแล้ว", "report", 2),
    ("Let me send you the file.", "ฉันส่งไฟล์ให้คุณ", "file", 1),
    ("Did you get a chance to see my email?", "ได้มีโอกาสดูอีเมลของฉันหรือยังครับ/ค่ะ", "chance", 2),
    ("I'll shoot you an email with the details.", "เดี๋ยวฉันส่งอีเมลบอกรายละเอียดให้นะ", "shoot", 2),
    ("Please reply as soon as possible.", "กรุณาตอบกลับโดยเร็ว", "reply", 2),
    ("Check your inbox.", "เช็คกล่องจดหมายของคุณ", "inbox", 2),
    ("I haven't checked my email yet.", "ฉันยังไม่ได้เช็คอีเมล", "checked", 2),
    ("Who's in charge here?", "ใครเป็นคนดูแลที่นี่", "charge", 3),
    ("I'll talk to my supervisor.", "ฉันจะคุยกับหัวหน้า", "supervisor", 3),
    ("I report to the manager.", "ฉันรายงานตรงต่อผู้จัดการ", "report", 3),
    ("Let me ask my boss.", "ขอถามเจ้านายก่อน", "boss", 1),
    ("I'll confirm with my team.", "ฉันจะยืนยันกับทีมก่อน", "confirm", 2),
    ("We're working on it.", "เรากำลังทำอยู่", "working", 1),
    ("The project is on track.", "โปรเจกต์เป็นไปตามแผน", "project", 2),
    ("We're behind schedule.", "เราช้ากว่าแผน", "behind", 2),
    ("We need more time.", "เราต้องใช้เวลามากกว่านี้", "time", 1),
    ("It will take a few days.", "ต้องใช้เวลาอีกสองสามวัน", "days", 2),
    ("I need a day off.", "ฉันขอลาหยุดหนึ่งวัน", "off", 1),
    ("I'm taking a sick day.", "ฉันขอลาป่วย", "sick", 2),
    ("I don't feel well today.", "วันนี้ฉันไม่สบาย", "well", 1),
    ("I feel much better now.", "ตอนนี้รู้สึกดีขึ้นมากแล้ว", "better", 1),
    ("I'm going on vacation next week.", "อาทิตย์หน้าฉันจะไปพักร้อน", "vacation", 2),
    ("Who's covering for you?", "ใครดูแลงานแทนคุณ", "covering", 3),
    ("Can you work overtime?", "ทำงานล่วงเวลาได้ไหม", "overtime", 2),
    ("I'll cover for you.", "ฉันช่วยรับช่วงงานให้", "cover", 3),
    ("Let's divide the work.", "แบ่งงานกันเถอะ", "divide", 3),
    ("That's not my job.", "นั่นไม่ใช่งานของฉัน", "job", 1),
    ("I'll handle it.", "ฉันจะจัดการเอง", "handle", 1),
    ("Can you handle this task?", "จัดการงานนี้ได้ไหม", "task", 2),
    ("I'll do my best.", "ฉันจะทำให้ดีที่สุด", "best", 1),
    ("We did a great job.", "เราทำได้ดีมาก", "great", 1),
    ("Great work everyone.", "ทุกคนทำงานได้ดีมาก", "Great", 1),
    ("Well done!", "ทำได้ดีมาก", "done", 1),
    ("Keep up the good work.", "ทำต่อไปนะ ทำได้ดี", "Keep", 2),
    ("You deserve a raise.", "คุณสมควรได้ขึ้นเงินเดือน", "raise", 3),
    ("I'd like a promotion.", "ฉันอยากได้เลื่อนตำแหน่ง", "promotion", 3),
    ("I'm looking for a job.", "ฉันกำลังหางาน", "job", 1),
    ("I got a new job.", "ฉันได้งานใหม่", "job", 1),
    ("I had a job interview today.", "วันนี้ฉันมีสัมภาษณ์งาน", "interview", 2),
    ("The interview went well.", "สัมภาษณ์ผ่านไปด้วยดี", "went", 2),
    ("I quit my job.", "ฉันลาออกจากงาน", "quit", 2),
    ("He was laid off due to company restructuring.", "เขาถูกเลิกจ้างเนื่องจากการปรับโครงสร้างบริษัท", "restructuring", 3),
    ("She resigned last month.", "เธอลาออกเมื่อเดือนที่แล้ว", "resigned", 3),
    ("We're hiring new staff.", "เรากำลังรับคนใหม่", "hiring", 2),
    ("What position are you applying for?", "คุณสมัครตำแหน่งอะไร", "position", 2),
    ("I'm a software developer.", "ฉันเป็นนักพัฒนาซอฟต์แวร์", "developer", 2),
    ("I work in marketing.", "ฉันทำงานสายการตลาด", "marketing", 2),
    ("I work in sales.", "ฉันทำงานสายขาย", "sales", 1),
    ("I'm self-employed.", "ฉันทำธุรกิจส่วนตัว", "self-employed", 3),
    ("I'm looking for a new opportunity.", "ฉันกำลังหาโอกาสใหม่", "opportunity", 3),
]),
]