# -*- coding: utf-8 -*-
# Part 3: study (55) + health (50) = 105

DATA = [
("study", "การเรียน การศึกษา", [
    ("I'm currently working on my bachelor's degree.", "ตอนนี้ฉันกำลังเรียนปริญญาตรีอยู่", "degree", 2),
    ("I go to university.", "ฉันเรียนมหาวิทยาลัย", "university", 1),
    ("What are you studying?", "คุณเรียนอะไรอยู่", "studying", 1),
    ("I'm studying English.", "ฉันเรียนภาษาอังกฤษ", "English", 1),
    ("My major is engineering.", "ฉันเรียนวิศวกรรมศาสตร์", "major", 2),
    ("What's your major?", "วิชาเอกของคุณคืออะไร", "major", 2),
    ("I'm in my third year.", "ฉันอยู่ปีสาม", "year", 2),
    ("I'm about to graduate.", "ฉันกำลังจะจบการศึกษา", "graduate", 2),
    ("When is the exam?", "สอบเมื่อไหร่", "exam", 1),
    ("I have an exam tomorrow.", "พรุ่งนี้ฉันมีสอบ", "exam", 1),
    ("I need to study hard.", "ฉันต้องขยันเรียน", "study", 1),
    ("I studied all night.", "ฉันอ่านหนังสือทั้งคืน", "studied", 2),
    ("Did you do your homework?", "ทำการบ้านหรือยัง", "homework", 1),
    ("I haven't done my homework yet.", "ฉันยังไม่ได้ทำการบ้าน", "homework", 1),
    ("The homework is due on Friday.", "การบ้านส่งวันศุกร์", "due", 2),
    ("Can you help me with this problem?", "ช่วยฉันทำข้อนี้หน่อยได้ไหม", "problem", 1),
    ("I don't understand this question.", "ฉันไม่เข้าใจคำถามนี้", "understand", 1),
    ("Could you explain it again?", "ช่วยอธิบายอีกครั้งได้ไหม", "explain", 1),
    ("I need more explanation.", "ฉันต้องการคำอธิบายเพิ่ม", "explanation", 2),
    ("Can you give me an example?", "ยกตัวอย่างให้หน่อยได้ไหม", "example", 1),
    ("I get it now.", "ตอนนี้ฉันเข้าใจแล้ว", "get", 1),
    ("I don't get it.", "ฉันไม่เข้าใจ", "get", 1),
    ("Let me think for a moment.", "ขอคิดแป๊บนึง", "moment", 1),
    ("What does this word mean?", "คำนี้หมายความว่าอะไร", "word", 1),
    ("How do you spell that?", "สะกดยังไง", "spell", 2),
    ("How do you pronounce this?", "ออกเสียงยังไง", "pronounce", 2),
    ("Please repeat after me.", "พูดตามฉันที", "repeat", 2),
    ("Can you speak more slowly?", "พูดช้าลงหน่อยได้ไหม", "slowly", 1),
    ("My speaking is not very good.", "การพูดของฉันยังไม่ค่อยดี", "speaking", 2),
    ("I need to practice speaking.", "ฉันต้องฝึกพูด", "practice", 1),
    ("Practice makes perfect.", "ฝึกฝนทำให้เก่ง", "Practice", 2),
    ("I want to improve my English.", "ฉันอยากพัฒนาภาษาอังกฤษ", "improve", 1),
    ("Your English is very good.", "ภาษาอังกฤษของคุณดีมาก", "good", 1),
    ("How long have you studied English?", "เรียนภาษาอังกฤษมานานแค่ไหน", "studied", 2),
    ("I've studied for five years.", "ฉันเรียนมาห้าปีแล้ว", "years", 1),
    ("Where did you learn English?", "เรียนภาษาอังกฤษที่ไหนมา", "learn", 1),
    ("I learned it at school.", "ฉันเรียนที่โรงเรียน", "school", 1),
    ("I watch movies to learn English.", "ฉันดูหนังเพื่อเรียนภาษาอังกฤษ", "movies", 1),
    ("Reading helps a lot.", "การอ่านช่วยได้มาก", "Reading", 2),
    ("I should read more.", "ฉันควรอ่านหนังสือมากกว่านี้", "read", 1),
    ("I have a lot of homework.", "ฉันมีการบ้านเยอะมาก", "homework", 1),
    ("The class was canceled.", "คาบเรียนถูกยกเลิก", "canceled", 2),
    ("The professor is very approachable and supportive.", "อาจารย์เข้าถึงง่ายและให้การสนับสนุนดีมาก", "approachable", 2),
    ("Our teacher gives clear explanations.", "ครูของเราอธิบายชัดเจน", "explanations", 3),
    ("Class starts at nine.", "เรียนเริ่มเก้าโมง", "starts", 1),
    ("Don't be late for class.", "อย่ามาเรียนสาย", "late", 1),
    ("I sat in the front row.", "ฉันนั่งแถวหน้า", "row", 2),
    ("Feel free to raise your hand if you have questions.", "ยกมือถามได้ตลอดเลยนะถ้ามีข้อสงสัย", "questions", 2),
    ("Who wants to answer?", "ใครอยากตอบ", "answer", 1),
    ("Let's work in pairs.", "ทำงานเป็นคู่กันเถอะ", "pairs", 2),
    ("We have a group project.", "เรามีโปรเจกต์กลุ่ม", "project", 2),
    ("The library is a good place to study.", "ห้องสมุดเป็นที่อ่านหนังสือที่ดี", "library", 2),
    ("I found this book helpful.", "หนังสือเล่มนี้ช่วยได้มาก", "helpful", 2),
    ("Let me look that up in an online dictionary.", "ขอฉันค้นดูในพจนานุกรมออนไลน์แป๊บนึง", "online", 2),
    ("I aced the exam with flying colors!", "ฉันสอบผ่านฉลุยได้คะแนนยอดเยี่ยมเลย!", "colors", 2),
]),
("health", "สุขภาพ หมอ", [
    ("I don't feel well.", "ฉันไม่ค่อยสบาย", "well", 1),
    ("I'm feeling under the weather today.", "วันนี้ฉันรู้สึกครั่นเนื้อครั่นตัว ไม่ค่อยสบาย", "weather", 2),
    ("I have a headache.", "ฉันปวดหัว", "headache", 1),
    ("I have a stomachache.", "ฉันปวดท้อง", "stomachache", 2),
    ("I have a sore throat.", "ฉันเจ็บคอ", "throat", 2),
    ("I have a fever.", "ฉันมีไข้", "fever", 1),
    ("I have a cold.", "ฉันเป็นหวัด", "cold", 1),
    ("I've been coughing a lot.", "ฉันไอเยอะมาก", "coughing", 2),
    ("I have a runny nose.", "ฉันน้ำมูกไหล", "nose", 2),
    ("I'm allergic to something.", "ฉันแพ้อะไรบางอย่าง", "allergic", 2),
    ("I need to see a doctor.", "ฉันต้องไปหาหมอ", "doctor", 1),
    ("Where is the hospital?", "โรงพยาบาลอยู่ที่ไหน", "hospital", 1),
    ("I need to make an appointment.", "ฉันต้องนัดพบหมอ", "appointment", 2),
    ("Can I book an appointment?", "จองคิวพบหมอได้ไหม", "book", 2),
    ("I'd like to see a doctor today.", "ฉันอยากพบหมอวันนี้", "today", 2),
    ("What are your symptoms?", "อาการของคุณเป็นยังไง", "symptoms", 2),
    ("Where does it hurt?", "เจ็บตรงไหน", "hurt", 1),
    ("I have a terrible backache from sitting at my desk all day.", "ฉันปวดหลังมากจากการนั่งทำงานที่โต๊ะทั้งวัน", "backache", 2),
    ("I'm having sharp chest pains.", "ฉันรู้สึกเจ็บแปล๊บที่หน้าอก", "sharp", 2),
    ("It hurts when I move.", "ขยับแล้วเจ็บ", "move", 2),
    ("How long have you felt this way?", "รู้สึกแบบนี้มานานแค่ไหน", "long", 2),
    ("I've been feeling like this for three days now.", "ฉันมีอาการแบบนี้มาสามวันติดแล้ว", "feeling", 2),
    ("Do you take any medicine?", "คุณทานยาอะไรอยู่ไหม", "medicine", 2),
    ("I'm taking some painkillers.", "ฉันทานยาแก้ปวดอยู่", "painkillers", 3),
    ("I need a prescription.", "ฉันต้องมีใบสั่งยา", "prescription", 3),
    ("Can you give me a prescription?", "สั่งยาให้ฉันได้ไหม", "prescription", 3),
    ("Take this medicine twice a day.", "ทานยานี้วันละสองครั้ง", "medicine", 2),
    ("Take it after meals.", "ทานหลังอาหาร", "meals", 2),
    ("Did you take your medicine?", "ทานยาแล้วหรือยัง", "take", 2),
    ("You should get some rest.", "คุณควรพักผ่อน", "rest", 1),
    ("Get plenty of rest.", "พักผ่อนให้มากๆ", "plenty", 2),
    ("Drink lots of water.", "ดื่มน้ำเยอะๆ", "water", 1),
    ("Stay in bed today.", "วันนี้นอนพักอยู่บนเตียง", "bed", 2),
    ("You'll feel better soon.", "เดี๋ยวคุณก็ดีขึ้น", "better", 1),
    ("I'm feeling better now.", "ตอนนี้ฉันรู้สึกดีขึ้นแล้ว", "better", 1),
    ("I feel much worse now.", "ตอนนี้แย่ลงกว่าเดิม", "worse", 2),
    ("I need to go to the hospital.", "ฉันต้องไปโรงพยาบาล", "hospital", 1),
    ("Call an ambulance!", "โทรเรียกรถพยาบาล", "ambulance", 2),
    ("Is it serious?", "อาการหนักไหม", "serious", 1),
    ("It's not serious.", "ไม่ได้เป็นอะไรร้ายแรง", "serious", 1),
    ("I have a broken arm.", "แขนฉันหัก", "broken", 2),
    ("I twisted my ankle.", "ข้อเท้าฉันเคล็ด", "ankle", 3),
    ("I can't move my leg.", "ขยับขาไม่ได้", "leg", 2),
    ("I need some medicine.", "ฉันต้องหายา", "medicine", 1),
    ("Where's the pharmacy?", "ร้านขายยาอยู่ที่ไหน", "pharmacy", 2),
    ("I'll get the medicine.", "ฉันจะไปซื้อยา", "medicine", 1),
    ("The doctor will see you now.", "หมอพร้อมพบคุณแล้ว", "see", 2),
    ("Open your mouth, please.", "อ้าปากหน่อย", "mouth", 2),
    ("Take a deep breath and try to relax your muscles.", "สูดหายใจเข้าลึกๆ แล้วพยายามผ่อนคลายกล้ามเนื้อนะ", "muscles", 2),
    ("You need to rest for a week.", "คุณต้องพักผ่อนหนึ่งอาทิตย์", "rest", 2),
]),
]