# -*- coding: utf-8 -*-
# Part 4: emotion (75) + polite (45) + opinion (30) = 150

DATA = [
("emotion", "อารมณ์ ความรู้สึก", [
    ("I'm so happy.", "ฉันมีความสุขมาก", "happy", 1),
    ("I'm excited about this.", "ฉันตื่นเต้นกับเรื่องนี้", "excited", 1),
    ("I feel great today.", "วันนี้ฉันรู้สึกดีมาก", "great", 1),
    ("I'm in a good mood.", "ฉันอารมณ์ดี", "mood", 1),
    ("I'm thrilled about the news.", "ฉันดีใจมากกับข่าวนี้", "thrilled", 2),
    ("I'm proud of you.", "ฉันภูมิใจในตัวคุณ", "proud", 1),
    ("I'm so proud of myself.", "ฉันภูมิใจในตัวเองมาก", "proud", 2),
    ("I'm satisfied with the result.", "ฉันพอใจกับผลลัพธ์", "satisfied", 2),
    ("I'm grateful for your help.", "ฉันรู้สึกขอบคุณในความช่วยเหลือของคุณ", "grateful", 2),
    ("I feel relieved.", "ฉันโล่งใจแล้ว", "relieved", 2),
    ("That's a relief.", "โล่งอกไปที", "relief", 2),
    ("I feel relaxed now.", "ตอนนี้ฉันรู้สึกผ่อนคลายแล้ว", "relaxed", 2),
    ("I'm having a good time.", "ฉันกำลังสนุกมาก", "having", 1),
    ("I'm having fun.", "ฉันสนุกมาก", "fun", 1),
    ("I'm looking forward to it.", "ฉันตั้งตารออยู่", "looking", 1),
    ("I can't wait!", "รอไม่ไหวแล้ว", "wait", 1),
    ("I feel sad.", "ฉันรู้สึกเศร้า", "sad", 1),
    ("I'm feeling down today.", "วันนี้ฉันรู้สึกหดหู่", "down", 2),
    ("I'm upset about it.", "ฉันเสียใจกับเรื่องนั้น", "upset", 2),
    ("I'm really disappointed with how things turned out.", "ฉันรู้สึกผิดหวังกับสิ่งที่เกิดขึ้นจริงๆ", "disappointed", 2),
    ("It's such a letdown after putting in so much hard work.", "น่าผิดหวังจริงๆ หลังจากที่เราทุ่มเททำงานหนักกันขนาดนี้", "letdown", 3),
    ("I feel lonely.", "ฉันรู้สึกเหงา", "lonely", 1),
    ("I miss you.", "ฉันคิดถึงคุณ", "miss", 1),
    ("I've missed you so much.", "ฉันคิดถึงคุณมาก", "missed", 1),
    ("I'm worried about you.", "ฉันเป็นห่วงคุณ", "worried", 1),
    ("I'm worried about the future.", "ฉันกังวลเกี่ยวกับอนาคต", "future", 2),
    ("I'm anxious about the test.", "ฉันกังวลเรื่องสอบ", "anxious", 2),
    ("I'm terrified of making a fool of myself in public.", "ฉันกลัวขายหน้าในที่สาธารณะมากเลย", "terrified", 2),
    ("That scared me.", "นั่นทำให้ฉันตกใจ", "scared", 2),
    ("I'm afraid of heights.", "ฉันกลัวที่สูง", "afraid", 2),
    ("Don't be afraid.", "อย่ากลัว", "afraid", 1),
    ("I'm furious that they went behind my back.", "ฉันโกรธมากที่พวกเขาทำอะไรลับหลังฉัน", "furious", 2),
    ("I'm really angry right now.", "ตอนนี้ฉันโกรธมาก", "angry", 1),
    ("Don't be angry with me.", "อย่าโกรธฉันเลย", "angry", 2),
    ("I'm frustrated because things aren't going according to plan.", "ฉันหงุดหงิดเพราะอะไรๆ ก็ไม่เป็นไปตามแผนที่วางไว้", "frustrated", 2),
    ("This is so frustrating.", "นี่มันน่าหงุดหงิดมาก", "frustrating", 2),
    ("I'm annoyed.", "ฉันรำคาญ", "annoyed", 2),
    ("It really gets on my nerves when people cut in line.", "มันชวนให้หงุดหงิดรำคาญใจจริงๆ เวลาคนแซงคิว", "nerves", 3),
    ("I can't stand it anymore.", "ฉันทนไม่ไหวแล้ว", "stand", 2),
    ("I've had enough.", "ฉันพอแล้ว", "enough", 2),
    ("I'm exhausted.", "ฉันเหนื่อยมาก", "exhausted", 1),
    ("I'm so tired.", "ฉันเหนื่อยมาก", "tired", 1),
    ("I feel burned out.", "ฉันรู้สึกหมดไฟ", "burned", 3),
    ("I need a break.", "ฉันต้องพักแล้ว", "break", 1),
    ("I'm stressed out.", "ฉันเครียดมาก", "stressed", 2),
    ("This is too stressful.", "นี่เครียดเกินไป", "stressful", 2),
    ("I feel overwhelmed.", "ฉันรู้สึกรับมือไม่ไหว / แบกรับไม่ไหว", "overwhelmed", 3),
    ("Take a deep breath.", "หายใจเข้าลึกๆ", "deep", 2),
    ("Calm down.", "ใจเย็นๆ", "Calm", 1),
    ("Relax, everything is fine.", "ผ่อนคลาย ทุกอย่างโอเค", "Relax", 2),
    ("It's not the end of the world.", "มันไม่ใช่จุดจบของโลก", "end", 3),
    ("It could be worse.", "มันอาจจะแย่กว่านี้ก็ได้", "worse", 1),
    ("There's always a next time.", "มีครั้งหน้าเสมอ", "next", 2),
    ("Don't give up.", "อย่ายอมแพ้", "give", 1),
    ("Keep going, you can do it.", "ไปต่อเถอะ ทำได้อยู่แล้ว", "Keep", 2),
    ("You can do it.", "คุณทำได้", "can", 1),
    ("I believe in you.", "ฉันเชื่อในตัวคุณ", "believe", 1),
    ("I'm proud of what you've achieved.", "ฉันภูมิใจในสิ่งที่คุณทำสำเร็จ", "achieved", 3),
    ("I understand how you feel.", "ฉันเข้าใจความรู้สึกของคุณ", "understand", 1),
    ("I'm here for you.", "ฉันอยู่ตรงนี้เพื่อคุณ", "here", 1),
    ("You're not alone.", "คุณไม่ได้อยู่คนเดียว", "alone", 1),
    ("It's okay to cry.", "ร้องไห้ได้ไม่ผิด", "cry", 2),
    ("Let it out.", "ระบายออกมาเถอะ", "out", 2),
    ("I'll support you no matter what.", "ฉันจะสนับสนุนคุณไม่ว่ายังไง", "support", 2),
    ("I'll always be by your side.", "ฉันจะอยู่ข้างคุณเสมอ", "side", 2),
    ("I feel grateful to have you.", "ฉันรู้สึกขอบคุณที่มีคุณ", "grateful", 2),
    ("You mean the world to me.", "คุณคือโลกทั้งใบของฉัน", "world", 2),
    ("I appreciate you.", "ฉันซาบซึ้งในตัวคุณ", "appreciate", 1),
    ("Thank you for being here.", "ขอบคุณที่อยู่ตรงนี้", "being", 1),
    ("I feel blessed.", "ฉันรู้สึกโชคดีและมีความสุขมาก", "blessed", 2),
    ("Life is beautiful.", "ชีวิตมันสวยงาม", "beautiful", 1),
    ("Stay positive.", "มองโลกในแง่ดี", "positive", 1),
    ("Focus on the silver lining, things will eventually improve.", "พยายามมองหาข้อดีในเรื่องร้ายนะ เดี๋ยวทุกอย่างก็จะดีขึ้นในที่สุด", "silver", 3),
    ("Every cloud has a silver lining.", "ฝนตกฟ้าดี ทุกปัญหามีทางออก", "silver", 3),
    ("Tomorrow is another day.", "พรุ่งนี้ก็ยังมีวันใหม่", "Tomorrow", 1),
]),
("polite", "การขอร้อง ขอบคุณ ขอโทษ", [
    ("Could you please do me a quick favor?", "ช่วยอะไรฉันสักอย่างได้ไหมครับ/ค่ะ", "favor", 2),
    ("Thank you, I couldn't have pulled it off without your help.", "ขอบคุณมากนะ ถ้าไม่มีคุณช่วยฉันคงทำไม่สำเร็จ", "without", 2),
    ("Thanks a million for lending a helping hand!", "ขอบคุณมากๆ จากใจเลยนะที่ช่วยยื่นมือเข้ามา!", "million", 2),
    ("Thank you so much.", "ขอบคุณมากๆ", "much", 1),
    ("I really appreciate it.", "ฉันซาบซึ้งมาก", "appreciate", 1),
    ("You're very kind.", "คุณใจดีมาก", "kind", 1),
    ("I owe you one.", "ฉันติดค้างคุณไว้ครั้งหนึ่งนะ / ไว้ฉันตอบแทนนะ", "owe", 2),
    ("You're more than welcome, glad I could be of help!", "ยินดีเป็นอย่างยิ่งเลย ดีใจที่ได้ช่วยนะ!", "welcome", 2),
    ("No problem.", "ไม่มีปัญหา", "problem", 1),
    ("Don't mention it.", "ไม่เป็นไร ไม่ต้องเกรงใจ", "mention", 2),
    ("It was nothing.", "เรื่องเล็กน้อยมากครับ / ไม่เป็นไรเลยครับ", "nothing", 2),
    ("Anytime.", "ยินดีเสมอครับ / ด้วยความยินดีเลย", "Anytime", 1),
    ("Excuse me.", "ขอโทษนะ / ขออนุญาต", "Excuse", 1),
    ("Pardon me.", "ขอโทษนะครับ/ค่ะ", "Pardon", 2),
    ("Sorry to bother you.", "ขอโทษที่รบกวน", "bother", 2),
    ("Sorry for the delay.", "ขอโทษที่ล่าช้า", "delay", 2),
    ("I'm truly sorry for the confusion and delay.", "ฉันต้องขอโทษจากใจจริงๆ สำหรับความสับสนและความล่าช้า", "confusion", 2),
    ("I apologize.", "ฉันขอโทษ", "apologize", 2),
    ("My apologies.", "ขอโทษด้วยครับ/ค่ะ", "apologies", 3),
    ("I'm really sorry.", "ฉันขอโทษจริงๆ", "really", 1),
    ("I'm sorry for what I said.", "ขอโทษที่พูดแบบนั้น", "said", 2),
    ("I didn't mean to hurt you.", "ฉันไม่ได้ตั้งใจจะทำร้ายคุณ", "hurt", 2),
    ("It was my fault.", "มันเป็นความผิดของฉัน", "fault", 2),
    ("Please forgive me.", "ได้โปรดยกโทษให้ฉัน", "forgive", 2),
    ("I won't let it happen again.", "ฉันจะไม่ให้มันเกิดขึ้นอีก", "again", 2),
    ("That's okay.", "ไม่เป็นไร", "okay", 1),
    ("It's no big deal, don't worry about it at all.", "ไม่ใช่เรื่องใหญ่อะไรเลย ไม่ต้องกังวลเลยนะ", "deal", 2),
    ("Forget about it.", "ลืมมันไปเถอะ", "Forget", 1),
    ("Never mind.", "ช่างเถอะ", "Never", 1),
    ("Could you help me?", "ช่วยฉันหน่อยได้ไหม", "help", 1),
    ("Would you mind helping me?", "ช่วยฉันหน่อยได้ไหม", "mind", 2),
    ("Can you do me a favor?", "ช่วยฉันหน่อยได้ไหม", "favor", 2),
    ("I need your help.", "ฉันต้องการความช่วยเหลือ", "help", 1),
    ("Can I ask you something?", "ถามอะไรหน่อยได้ไหม", "ask", 1),
    ("May I ask a question?", "ขอถามคำถามได้ไหม", "question", 2),
    ("May I come in?", "เข้าไปได้ไหม", "come", 2),
    ("Could I use your phone?", "ขอยืมโทรศัพท์หน่อยได้ไหม", "use", 2),
    ("Is it okay if I sit here?", "นั่งตรงนี้ได้ไหม", "sit", 2),
    ("Do you mind if I open the window?", "เปิดหน้าต่างได้ไหม", "open", 2),
    ("Please be quiet.", "กรุณาเงียบๆ หน่อย", "quiet", 2),
    ("Please wait for me.", "กรุณารอฉันด้วย", "wait", 1),
    ("Please don't go.", "ได้โปรดอย่าไป", "go", 1),
    ("Come with me, please.", "มากับฉันหน่อย", "Come", 1),
    ("Help me, please.", "ช่วยฉันด้วย", "Help", 1),
]),
("opinion", "แสดงความคิดเห็น", [
    ("I think so.", "ฉันคิดว่าใช่", "think", 1),
    ("I don't think so.", "ฉันว่าไม่ใช่", "think", 1),
    ("I couldn't agree with you more on this point.", "เรื่องนี้ฉันเห็นด้วยกับประเด็นของคุณอย่างยิ่งเลย", "agree", 2),
    ("I see things a bit differently from your perspective.", "ฉันมองต่างออกไปจากมุมมองของคุณนิดหน่อยนะ", "differently", 2),
    ("I agree with you.", "ฉันเห็นด้วยกับคุณ", "agree", 1),
    ("I don't agree with that.", "ฉันไม่เห็นด้วยกับสิ่งนั้น", "agree", 2),
    ("That's a very valid point you just raised.", "นั่นเป็นประเด็นที่มีน้ำหนักและน่าคิดมากที่คุณเพิ่งยกขึ้นมา", "valid", 2),
    ("You hit the nail right on the head.", "คุณพูดได้ตรงเป๊ะ ถูกจุดเลย", "nail", 3),
    ("You're right.", "คุณพูดถูก", "right", 1),
    ("I'm afraid that information isn't entirely accurate.", "เกรงว่าข้อมูลนั้นอาจจะไม่ถูกต้องทั้งหมดครับ/ค่ะ", "accurate", 2),
    ("I'm not sure.", "ฉันไม่แน่ใจ", "sure", 1),
    ("Maybe you're right.", "บางทีคุณอาจจะถูก", "Maybe", 1),
    ("I doubt it.", "ฉันคิดว่าคงไม่ / ไม่น่าจะใช่นะ", "doubt", 2),
    ("I'm not convinced.", "ฉันยังไม่เชื่อ", "convinced", 3),
    ("It depends.", "แล้วแต่สถานการณ์", "depends", 2),
    ("That makes sense.", "นั่นสมเหตุสมผล", "sense", 1),
    ("That doesn't make sense.", "นั่นไม่สมเหตุสมผล", "sense", 1),
    ("I see your point.", "ฉันเข้าใจประเด็นของคุณ", "point", 1),
    ("Good point.", "ประเด็นดี", "point", 1),
    ("Fair enough.", "ก็สมเหตุสมผลดี / เข้าใจได้", "Fair", 2),
    ("Let's agree to disagree.", "ถือว่าเราเห็นต่างกันนะ / ต่างคนต่างความคิดนะ", "disagree", 3),
    ("In my opinion...", "ในความคิดของฉัน...", "opinion", 2),
    ("From my point of view...", "จากมุมมองของฉัน...", "point", 3),
    ("As far as I know...", "เท่าที่ฉันรู้...", "know", 2),
    ("To be honest...", "พูดตรงๆ นะ...", "honest", 2),
    ("Honestly speaking...", "พูดตามตรง...", "Honestly", 3),
    ("It's up to you.", "แล้วแต่คุณ", "up", 1),
    ("Whatever you decide is fine.", "คุณตัดสินใจอะไรก็ได้", "decide", 2),
    ("Both are good options.", "ทั้งสองตัวเลือกก็ดีทั้งคู่", "options", 2),
    ("I'll go with your suggestion.", "ฉันจะทำตามข้อเสนอของคุณ", "suggestion", 3),
]),
]