# -*- coding: utf-8 -*-
# Part 5: movie (100) + time (45) + weather (30) + money (45) = 220

DATA = [
("movie", "ประโยคในหนัง ซีรีส์", [
    ("Trust me on this, I know exactly what I'm doing.", "เชื่อใจฉันในเรื่องนี้เถอะ ฉันรู้ชัดเจนว่ากำลังทำอะไรอยู่", "Trust", 2),
    ("I promise you won't regret taking this chance.", "ฉันสัญญาเลยว่าคุณจะไม่เสียใจที่คว้าโอกาสนี้ไว้", "promise", 2),
    ("I swear I had nothing to do with what happened.", "ฉันสาบานได้เลยว่าฉันไม่มีส่วนเกี่ยวข้องกับสิ่งที่เกิดขึ้น", "swear", 2),
    ("Are you serious?", "คุณพูดจริงเหรอ", "serious", 1),
    ("You're kidding, right?", "คุณล้อเล่นใช่ไหม", "kidding", 1),
    ("I'm serious.", "ฉันพูดจริง", "serious", 1),
    ("I mean it.", "ฉันพูดจริงนะ", "mean", 1),
    ("That's impossible.", "เป็นไปไม่ได้", "impossible", 1),
    ("No way!", "ไม่มีทาง", "way", 1),
    ("It can't be true.", "มันต้องไม่จริง", "true", 2),
    ("I can't believe it.", "ฉันไม่อยากเชื่อ", "believe", 1),
    ("Unbelievable!", "เหลือเชื่อ", "Unbelievable", 2),
    ("That's incredible.", "เหลือเชื่อมาก", "incredible", 2),
    ("That blew my mind, absolutely incredible!", "เรื่องนั้นทำให้ฉันทึ่งจนอ้าปากค้างไปเลย สุดยอดจริงๆ!", "mind", 2),
    ("That's amazing!", "น่าทึ่งมาก", "amazing", 1),
    ("Couldn't be better, everything is spot on!", "ไม่มีอะไรจะดีไปกว่านี้แล้ว ทุกอย่างเป๊ะสุดๆ!", "spot", 2),
    ("Keep up the fantastic work, everyone!", "ผลงานยอดเยี่ยมมาก ทำดีแบบนี้ต่อไปนะทุกคน!", "fantastic", 2),
    ("You completely nailed it, outstanding performance!", "คุณทำได้ยอดเยี่ยมเฉียบคมมาก การแสดงผลงานโดดเด่นจริงๆ!", "nailed", 2),
    ("That was a stroke of genius, pure brilliance!", "นั่นเป็นความคิดที่ฉลาดล้ำเลิศจริงๆ ยอดเยี่ยมมาก!", "genius", 3),
    ("That's brilliant.", "เยี่ยมมาก", "brilliant", 2),
    ("Get out of here!", "ออกไปจากที่นี่", "out", 1),
    ("Get lost!", "ไปให้พ้น", "lost", 2),
    ("Leave me alone.", "ปล่อยฉันไว้ตามลำพัง", "alone", 1),
    ("Stay away from me.", "อยู่ห่างๆ ฉันไว้", "away", 1),
    ("Don't touch me!", "อย่ามาแตะต้องฉัน", "touch", 1),
    ("Back off!", "ถอยไป", "Back", 2),
    ("Give it back!", "คืนมันมา", "back", 1),
    ("Hey, that belongs to me, please put it back.", "เฮ้ อันนั้นเป็นของฉันนะ ช่วยวางคืนที่เดิมด้วย", "belongs", 2),
    ("That's mine.", "นั่นของฉัน", "mine", 1),
    ("Finders keepers.", "ใครเจอได้ก็เป็นของคนนั้น", "Finders", 3),
    ("I found it first.", "ฉันเจอมันก่อน", "found", 2),
    ("Keep an eye on him.", "จับตาดูเขาไว้", "eye", 2),
    ("Watch your step, the floor is wet and slippery!", "ระวังลื่นนะ พื้นมันเปียกและลื่นมาก!", "slippery", 2),
    ("Keep an eye out for oncoming traffic as you cross.", "คอยระวังรถที่วิ่งสวนมาด้วยนะตอนข้ามถนน", "traffic", 2),
    ("Be careful.", "ระวังให้ดี", "careful", 1),
    ("Careful what you wish for.", "ระวังสิ่งที่คุณอธิษฐานไว้", "wish", 3),
    ("Run for your life, there's no time to lose!", "วิ่งหนีเอาชีวิตรอดเร็ว ไม่มีเวลาให้ลังเลแล้ว!", "life", 2),
    ("Hurry up!", "รีบหน่อย", "Hurry", 1),
    ("Let's go!", "ไปกันเถอะ", "go", 1),
    ("Come on!", "เร็วเข้า / ไม่เอาน่า", "Come", 1),
    ("Follow me.", "ตามฉันมา", "Follow", 1),
    ("Stay right where you are until back-up arrives.", "อยู่ตรงนั้นนิ่งๆ นะจนกว่ากำลังเสริมจะมาถึง", "arrives", 2),
    ("Freeze! Don't make any sudden movements.", "หยุดตรงนั้น! อย่าขยับตัวกะทันหันนะ", "movements", 2),
    ("Freeze and drop your weapon immediately!", "หยุดและวางอาวุธลงทันทีเดี๋ยวนี้!", "weapon", 3),
    ("Put your hands up!", "ยกมือขึ้น", "hands", 2),
    ("Keep your hands where I can see them!", "เอามือไว้ในที่ที่ฉันมองเห็นได้ตลอด!", "Keep", 2),
    ("Stop right there!", "หยุดตรงนั้น", "Stop", 1),
    ("Hold it right there.", "หยุดอยู่ตรงนั้น", "Hold", 2),
    ("You're under arrest.", "คุณถูกจับกุม", "arrest", 3),
    ("You have the right to remain silent.", "คุณมีสิทธิ์ที่จะนิ่งเงียบ", "silent", 3),
    ("He got away.", "เขาหนีไปได้", "away", 2),
    ("Let him go.", "ปล่อยเขาไป", "go", 1),
    ("It's a trap!", "มันคือกับดัก", "trap", 2),
    ("We've been set up.", "เราโดนจัดฉากเข้าแล้ว / เราติดกับแล้ว", "set", 3),
    ("There's no escape.", "ไม่มีทางหนี", "escape", 2),
    ("I'm not afraid of you.", "ฉันไม่กลัวคุณ", "afraid", 1),
    ("You'll regret this.", "คุณจะเสียใจในภายหลัง", "regret", 2),
    ("This isn't over yet.", "เรื่องยังไม่จบ", "over", 2),
    ("It's not over until I say so.", "ยังไม่จบจนกว่าฉันจะบอกว่าจบ", "until", 3),
    ("Say that again, I dare you.", "แน่จริงพูดอีกรอบสิ / ถ้ากล้าก็ลองพูดอีกทีสิ", "dare", 3),
    ("You started this.", "คุณเริ่มเรื่องนี้เอง", "started", 2),
    ("This is your fault.", "นี่เป็นความผิดของคุณ", "fault", 1),
    ("It's all your fault.", "มันเป็นความผิดของคุณทั้งหมด", "fault", 2),
    ("Why did you do that?", "ทำไมคุณทำแบบนั้น", "why", 1),
    ("What have you done?", "คุณทำอะไรลงไป", "done", 1),
    ("What were you thinking?", "คุณคิดอะไรอยู่", "thinking", 1),
    ("I didn't do it.", "ฉันไม่ได้ทำ", "do", 1),
    ("I had no choice.", "ฉันไม่มีทางเลือก", "choice", 2),
    ("You made me do it.", "คุณบังคับให้ฉันทำ", "made", 2),
    ("It was self-defense.", "มันเป็นการป้องกันตัว", "self-defense", 3),
    ("I'm telling the truth.", "ฉันพูดความจริง", "truth", 1),
    ("Tell me the truth.", "บอกความจริงมา", "truth", 1),
    ("I never lie.", "ฉันไม่เคยโกหก", "lie", 2),
    ("Don't lie to me.", "อย่าโกหกฉัน", "lie", 1),
    ("I wouldn't lie to you.", "ฉันไม่มีทางโกหกคุณหรอก", "wouldn't", 2),
    ("I'm not lying.", "ฉันไม่ได้โกหก", "lying", 1),
    ("Cross my heart.", "สาบานได้เลย", "Cross", 2),
    ("Honest to God.", "จริง ๆ สาบานได้", "Honest", 3),
    ("I'm being honest with you.", "ฉันพูดตรงๆ กับคุณ", "honest", 2),
    ("Listen to me.", "ฟังฉันก่อน", "Listen", 1),
    ("Hear me out.", "ฟังฉันให้จบก่อน", "Hear", 2),
    ("Look at me.", "มองฉันสิ", "Look", 1),
    ("Look me in the eye.", "มองตาฉันตรงๆ", "eye", 2),
    ("Talk to me.", "คุยกับฉันหน่อย", "Talk", 1),
    ("Don't ignore me.", "อย่าทำเป็นไม่สนใจฉัน", "ignore", 2),
    ("Answer me straight, stop beating around the bush!", "ตอบฉันมาตรงๆ อย่ามัวพูดจาอ้อมค้อม!", "bush", 3),
    ("What's the matter?", "มีอะไรหรือเปล่า", "matter", 1),
    ("What's wrong?", "เป็นอะไรไป", "wrong", 1),
    ("What happened?", "เกิดอะไรขึ้น", "happened", 1),
    ("What's going on?", "เกิดอะไรขึ้น", "going", 1),
    ("What's the problem?", "ปัญหาคืออะไร", "problem", 1),
    ("Is something wrong?", "มีอะไรผิดปกติหรือเปล่า", "something", 2),
    ("Everything is fine.", "ทุกอย่างโอเค", "Everything", 1),
    ("Nothing is wrong.", "ไม่มีอะไรผิดปกติ", "Nothing", 1),
    ("Calm down and tell me.", "ใจเย็นๆ แล้วเล่าให้ฟัง", "Calm", 2),
    ("It's not what you think.", "มันไม่ใช่อย่างที่คุณคิด", "think", 2),
    ("Let me explain.", "ขอฉันอธิบาย", "explain", 1),
    ("There's a good reason.", "มีเหตุผลที่ดีอยู่", "reason", 2),
    ("I can explain everything.", "ฉันอธิบายทุกอย่างได้", "explain", 2),
    ("Hear me out first.", "ฟังฉันให้จบก่อน", "first", 2),
]),
("time", "เวลา นัดหมาย", [
    ("What time is it?", "กี่โมงแล้ว", "time", 1),
    ("Do you have the time?", "มีเวลาหรือเปล่า", "time", 1),
    ("It's three o'clock.", "สามโมง", "o'clock", 1),
    ("It's half past three.", "สามโมงครึ่ง", "half", 2),
    ("It's quarter to four.", "อีกสิบห้านาทีสี่โมง (บ่ายสามสี่สิบห้า)", "quarter", 3),
    ("It's almost noon.", "ใกล้เที่ยงแล้ว", "noon", 2),
    ("It's getting late.", "ดึกแล้ว", "late", 1),
    ("It's early in the morning.", "เป็นช่วงเช้าตรู่", "early", 2),
    ("I'll be there on time.", "ฉันจะไปให้ตรงเวลา", "time", 1),
    ("Are you on time?", "คุณมาตรงเวลาไหม", "time", 1),
    ("I'm five minutes late.", "ฉันสายไปห้านาที", "late", 1),
    ("What time do you get up?", "ตื่นกี่โมง", "get", 1),
    ("What time do you go to bed?", "เข้านอนกี่โมง", "bed", 1),
    ("What time does the meeting start?", "ประชุมเริ่มกี่โมง", "start", 1),
    ("When does it begin?", "เริ่มเมื่อไหร่", "begin", 2),
    ("When does it end?", "จบเมื่อไหร่", "end", 1),
    ("How much time do we have?", "เรามีเวลาเท่าไหร่", "time", 2),
    ("We have plenty of time.", "เรามีเวลาเหลือเฟือ", "plenty", 2),
    ("We're running out of time.", "เวลาเราใกล้หมดแล้ว", "running", 2),
    ("Time is almost up.", "เวลาใกล้หมดแล้ว", "up", 2),
    ("Hurry, we're late!", "รีบหน่อย เราสายแล้ว", "Hurry", 1),
    ("We made it just in time.", "เรามาทันเวลาพอดี", "made", 2),
    ("We missed it by a minute.", "เราพลาดไปแค่นาทีเดียว", "missed", 3),
    ("I need more time.", "ฉันต้องการเวลามากกว่านี้", "time", 1),
    ("Give me a moment.", "ให้เวลาฉันแป๊บนึง", "moment", 1),
    ("Wait a second.", "รอแป๊บนึง", "second", 1),
    ("Just a minute.", "แป๊บนึง", "minute", 1),
    ("One moment, please.", "รอสักครู่", "moment", 1),
    ("I'll be done in a minute.", "ฉันจะเสร็จในอีกหนึ่งนาที", "done", 1),
    ("It'll only take a moment.", "ใช้เวลาแป๊บเดียว", "moment", 2),
    ("Let's meet at five.", "เจอกันห้าโมง", "five", 1),
    ("Let's meet at noon.", "เจอกันตอนเที่ยง", "noon", 1),
    ("See you in an hour.", "เจอกันในอีกหนึ่งชั่วโมง", "hour", 1),
    ("See you at eight.", "เจอกันสองทุ่ม", "eight", 1),
    ("Let's set a time.", "กำหนดเวลาไว้เลย", "set", 2),
    ("When is a good time for you?", "เวลาไหนสะดวกสำหรับคุณ", "good", 2),
    ("Does this time work for you?", "เวลานี้สะดวกไหม", "work", 2),
    ("I'm free in the afternoon.", "ฉันว่างช่วงบ่าย", "afternoon", 1),
    ("I'm busy in the morning.", "ช่วงเช้าฉันยุ่ง", "morning", 1),
    ("Let's do it another day.", "ไว้ทำวันอื่นเถอะ", "another", 2),
    ("See you soon.", "แล้วเจอกันเร็วๆ นี้", "soon", 1),
    ("See you later.", "แล้วเจอกัน", "later", 1),
    ("It's time to go.", "ถึงเวลาไปแล้ว", "time", 1),
    ("Time flies.", "เวลาผ่านไปไวจัง", "flies", 3),
    ("Where did the time go?", "เวลาหายไปไหนหมด", "time", 2),
]),
("weather", "สภาพอากาศ", [
    ("How's the weather?", "อากาศเป็นยังไง", "weather", 1),
    ("What's the weather like today?", "วันนี้อากาศเป็นยังไง", "weather", 1),
    ("It's sunny today.", "วันนี้แดดดี", "sunny", 1),
    ("It's a beautiful day.", "วันนี้อากาศดีมาก", "beautiful", 1),
    ("It's overcast and gloomy today, looks like rain.", "วันนี้ท้องฟ้ามืดครึ้มหม่นหมอง ดูเหมือนฝนจะตก", "overcast", 2),
    ("It's pouring cats and dogs outside, grab an umbrella!", "ข้างนอกฝนตกหนักไม่ลืมหูลืมตา พกร่มไปด้วยนะ!", "pouring", 2),
    ("It's pouring outside.", "ฝนตกหนักมาก", "pouring", 2),
    ("It's drizzling.", "ฝนตกปรอยๆ", "drizzling", 3),
    ("Take an umbrella with you.", "เอาร่มไปด้วย", "umbrella", 2),
    ("It's windy today.", "วันนี้ลมแรง", "windy", 1),
    ("The wind is strong.", "ลมแรงมาก", "strong", 2),
    ("It's hot outside.", "ข้างนอกร้อน", "hot", 1),
    ("It's really hot today.", "วันนี้ร้อนมาก", "hot", 1),
    ("It's cold today.", "วันนี้หนาว", "cold", 1),
    ("It's freezing outside.", "ข้างนอกหนาวมาก", "freezing", 2),
    ("The temperature is dropping.", "อุณหภูมิกำลังลดลง", "temperature", 3),
    ("It's getting warmer.", "อากาศเริ่มอุ่นขึ้น", "warmer", 2),
    ("What's the temperature?", "อุณหภูมิเท่าไหร่", "temperature", 2),
    ("It's about thirty degrees.", "ประมาณสามสิบองศา", "degrees", 2),
    ("It's humid today.", "วันนี้อากาศชื้น", "humid", 2),
    ("The weather is perfect.", "อากาศสมบูรณ์แบบ", "perfect", 1),
    ("The forecast says rain.", "พยากรณ์อากาศว่าฝนจะตก", "forecast", 2),
    ("It might rain later.", "เดี๋ยวอาจมีฝนตก", "rain", 1),
    ("It's going to rain.", "กำลังจะฝนตก", "rain", 1),
    ("I hope it doesn't rain.", "หวังว่าฝนจะไม่ตก", "hope", 1),
    ("We got caught in the rain.", "เราโดนฝน", "caught", 2),
    ("The storm is coming.", "พายุกำลังมา", "storm", 2),
    ("There's a thunderstorm tonight.", "คืนนี้มีพายุฟ้าคะนอง", "thunderstorm", 3),
    ("Did you hear the thunder?", "ได้ยินเสียงฟ้าร้องไหม", "thunder", 3),
    ("The sun is shining.", "แดดกำลังส่อง", "shining", 2),
]),
("money", "เงิน การเงิน", [
    ("How much does it cost?", "ราคาเท่าไหร่", "cost", 1),
    ("It comes out to ten dollars total.", "คิดเป็นเงินทั้งหมดสิบดอลลาร์", "total", 1),
    ("That's way beyond my budget, I can't afford it.", "อันนั้นเกินงบประมาณของฉันไปเยอะเลย ฉันจ่ายไม่ไหวหรอก", "budget", 2),
    ("I can't afford it.", "ฉันไม่สามารถจ่ายได้", "afford", 2),
    ("It's a bargain.", "ถูกมาก", "bargain", 2),
    ("It's worth it.", "คุ้มค่า", "worth", 1),
    ("It's not worth it.", "ไม่คุ้ม", "worth", 2),
    ("Do you have any money?", "มีเงินไหม", "money", 1),
    ("I don't carry any cash on me.", "ฉันไม่มีเงินสดติดตัวเลย", "carry", 2),
    ("I'm broke.", "ฉันไม่มีเงินติดตัว", "broke", 2),
    ("I'm short on cash.", "ฉันเงินไม่พอ", "short", 2),
    ("Can I borrow some money?", "ขอยืมเงินหน่อยได้ไหม", "borrow", 2),
    ("Can you lend me your car?", "ขอยืมรถของคุณได้ไหม", "lend", 3),
    ("I'll pay you back.", "ฉันจะคืนเงินให้", "pay", 1),
    ("You owe me ten dollars.", "คุณติดเงินฉันสิบดอลลาร์", "owe", 2),
    ("I need to save money.", "ฉันต้องเก็บเงิน", "save", 1),
    ("I'm saving up for a car.", "ฉันกำลังเก็บเงินซื้อรถ", "saving", 2),
    ("I spent too much.", "ฉันใช้เงินมากเกินไป", "spent", 2),
    ("I wasted my money.", "ฉันเสียเงินเปล่า", "wasted", 2),
    ("I got a good deal.", "ฉันได้ข้อตกลงที่ดี", "deal", 2),
    ("It was fifty percent off, what a steal!", "ลดตั้งห้าสิบเปอร์เซ็นต์ คุ้มสุดๆ ไปเลย!", "steal", 2),
    ("It's on sale this week.", "อาทิตย์นี้ลดราคา", "sale", 1),
    ("Do you accept contactless payments or QR codes?", "รับการชำระเงินแบบแตะจ่ายหรือสแกนคิวอาร์โค้ดไหมครับ/ค่ะ", "contactless", 2),
    ("Do you take credit cards?", "รับบัตรเครดิตไหม", "credit", 2),
    ("Can I pay in cash?", "จ่ายเงินสดได้ไหม", "cash", 1),
    ("I need to withdraw money.", "ฉันต้องกดเงิน", "withdraw", 2),
    ("Where's the ATM?", "ตู้ ATM อยู่ที่ไหน", "ATM", 2),
    ("I need to exchange money.", "ฉันต้องแลกเงิน", "exchange", 2),
    ("What's the exchange rate?", "อัตราแลกเปลี่ยนเท่าไหร่", "rate", 2),
    ("Can I get a receipt?", "ขอใบเสร็จได้ไหม", "receipt", 1),
    ("Could I request a full refund to my original payment method?", "ขอรับเงินคืนเต็มจำนวนกลับเข้าช่องทางชำระเงินเดิมได้ไหมครับ/ค่ะ", "refund", 2),
    ("That's a fair price.", "ราคายุติธรรม", "fair", 2),
    ("Money doesn't grow on trees.", "เงินไม่ได้เกิดจากต้นไม้", "trees", 3),
    ("Save for a rainy day.", "เก็บออมไว้ยามฉุกเฉิน", "rainy", 3),
    ("I'm trying to budget.", "ฉันกำลังพยายามจัดงบ", "budget", 2),
    ("We need to cut costs.", "เราต้องลดค่าใช้จ่าย", "costs", 2),
    ("It's a good investment.", "เป็นการลงทุนที่ดี", "investment", 3),
    ("The price went up.", "ราคาขึ้นแล้ว", "price", 2),
    ("The price went down.", "ราคาลงแล้ว", "price", 2),
    ("I can't pay my bills.", "ฉันจ่ายบิลไม่ไหว", "bills", 2),
    ("I'll pay the bill.", "ฉันจะจ่ายบิลเอง", "bill", 1),
    ("Let's split the cost.", "แบ่งจ่ายกันเถอะ", "cost", 2),
    ("Let's go Dutch.", "แยกจ่ายกัน", "Dutch", 3),
    ("It's my treat.", "ฉันเลี้ยงเอง", "treat", 2),
    ("Let me treat you.", "ให้ฉันเลี้ยงเอง", "treat", 2),
]),
]